### ISSUE TITLE
VS Code 1.79.1 incompatible

### ISSUE THREAD

**Issue by LjeDamos** [LeoDreamer2004/kubejs-item-completion#1]
Cannot install extension in VS Code with following error:
`Can't install 'leodreamer.kubejs-item-completion' extension because it is not compatible with the current version of Visual Studio Code (version 1.79.1).`

**Comment by LeoDreamer2004** [comment]
Update your VSCode to the latest version (at least 1.90.0)

**Comment by LjeDamos** [comment]
ty
